server:
  port: 8081
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.85.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_pms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
  rabbitmq:
    host: 106.54.238.192
    username: gmall
    password: gmall
    virtual-host: /gmall
    template:
      exchange: gmall.item.exchange  # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
    publisher-confirms: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

aliyun:
  oss:
    file:
      bucketname: chucai-public
      endpoint: oss-cn-beijing.aliyuncs.com
      filehost: gmall
      keyid: LTAIbD6T4nGJrIlr
      keysecret: S9Xmjhc7k0s9qVXVfior2GPURTcUNF